version: '3.8'

services:
  api:
    image: python:3.8-slim
    container_name: ocr_api
    restart: always
    ports:
      - "${PORT}:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: api.py
    working_dir: /app
    command: >
      sh -c "
      pip install -r requirements.txt &&
      flask run --host=0.0.0.0
      "